USE ORG;
SELECT * FROM Worker;

-- USE JOIN WITHOUT USING `JOIN` KEYWORD
-- HORIZONTAL JOIN, NO OF COLUMNS INCREASE
-- SELECT * FROM LEFTTABLE , RIGHT TABLE WHERE CONDITION
SELECT * FROM WORKER AS W, BONUS AS B WHERE W.WORKER_ID=B.WORKER_REF_ID; 

-- SET OPERATIONS (SET IS GROUP OF UNIQUE ENTITIES)
-- SET OPERATIONS CAN BE APPLIED ONLY IF NOW OF COLUMNS ARE SAME
-- SET OPERATIONS COMBINES TWO OR MORE SELECT STATEMENTS.
-- SET OPERATIONS ARE APPLIED ON ROWS.
	-- UNION
    -- INTERSECION
    -- MINUS
    
SELECT * FROM TABLE1 UNION SELECT * FROM TABLE2; -- `TABLE1` AND `TABLE2` SHOULD HAVE SAME COLUMNS

-- INTERSECT
SELECT  DISTINCT * FROM TABLE1 INNER JOIN TABLE2 USING(ID) ;

-- MINUS
SELECT ID FROM T1 LEFT JOIN T2 USING(ID) WHERE T2.ID IS NULL;
