-- SUB QUERIES
	-- Alternative Method to joins
	-- Outer Query(INNER QUERY) , GENERALLY OUTER QUERY DEPENDS ON INNER QUERY.
    -- Joins are faster, Subqueries are slower.
    -- Joins maximise calculation burden on DBMS, Subqueries keeps responsibility of calculation on user.
    -- Joins are Complex and difficult, subquries are easy to understand and implement.

USE ORG;

SELECT BONUS_AMOUNT FROM bonus;

SELECT * FROM WORKER WHERE WORKER_ID IN (SELECT WORKER_ID FROM WORKER WHERE SALARY>0);
SELECT * FROM WORKER WHERE WORKER_ID IN ( SELECT WORKER_REF_ID FROM bonus GROUP BY WORKER_REF_ID ) HAVING FIRST_NAME='Monika' ;

SELECT * FROM WORKER WHERE WORKER_ID IN (SELECT WORKER_REF_ID FROM bonus where BONUS_AMOUNT > 3000 );

SELECT Max(BONUS_AMOUNT) 

-- FROM CLAUSE -- DERIVED TABLE, SHOULD HAVE AN ALIAS
FROM (SELECT * FROM Bonus WHERE BONUS_AMOUNT > 0) AS subquery_alias;

-- CORELATED SUBQUERY
-- FOR ONE VALUE OF OUTER QUERY , INNER QUERY WILL RUN COMPLETELY ONE TIME.
SELECT * FROM WORKER W1 WHERE 9= (SELECT COUNT(W2.WORKER_ID) FROM WORKER W2 WHERE W2.WORKER_ID >= W1.WORKER_ID );



